name: Delete Neon Branches
description: Delete all associated Neon branches when a GitHub branch is deleted
inputs:
  api-key:
    required: true
  project-id:
    required: true
runs:
  using: node16
  main: zdist/index.js
