name: CI

on:
  push:
    branches-ignore:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project:
          - replay

    defaults:
      run:
        working-directory: ${{ matrix.project }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        run: npm ci

      - name: Run style checks
        run: npm run format:check

      - name: Build the project
        run: npm run build

      # Check that there are not any modified files after running `build`
      - name: Check for modified files
        run: |
          git diff --exit-code
